apiVersion: v1
data:
  myname: dinesh patil
  function: {{ .Values.function1}}
  location: {{ .Values.infra.location | upper | quote }} 
  date: {{ now | date "02-06-01" | quote  }}
  COMPANY: {{ .Values.company | default "NTMS" | upper | quote }}
  {{ if eq .Values.infra.location "mumbai"}}sub-location: powai {{ end }}
  Language: |-
    {{- range $index, $lang := .Values.Language }}
    - {{ $index }}: {{ $lang }}
    {{- end}}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name}}-configmap

  
