apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxcm
  name: nginxcm
spec:
  containers:
  - envFrom:
    - configMapRef:
          name: cmfromfile
    image: nginx
    name: nginxcm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
