apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvol
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dinesh/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: myvol
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
 name: hostpath-pd
spec:
 containers:
 - image: nginx
   name: hostpath-pd
   volumeMounts:
   - mountPath: /data
     name: test-volume
 volumes:
 - name: test-volume
   persistentVolumeClaim:
     claimName: myvol
