apiVersion: v1
kind: PersistentVolume
metadata:
  name: mygoldvol
spec:
  storageClassName: gold
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dinesh/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mygoldpvc
spec:
 storageClassName: gold
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
 name: hostpath-pd-pv
spec:
 containers:
 - image: nginx
   name: hostpath-pd
   volumeMounts:
   - mountPath: /data
     name: test-volume
 volumes:
 - name: test-volume
   persistentVolumeClaim:
     claimName: mygoldpvc


# Check out what error exist in above pods